"""


Django settings for selfWebsite project.



Generated by 'django-admin startproject' using Django 3.2.5.



For more information on this file, see


https://docs.djangoproject.com/en/3.2/topics/settings/



For the full list of settings and their values, see


https://docs.djangoproject.com/en/3.2/ref/settings/


"""



from pathlib import Path
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.


BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production


# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!


SECRET_KEY = os.environ['DJANGO_SECRET_KEY']



# SECURITY WARNING: don't run with debug turned on in production!


# DEBUG = False
DEBUG = True



# ALLOWED_HOSTS = ['prabals.herokuapp.com','127.0.0.1']
ALLOWED_HOSTS = ['*']




# Application definition



INSTALLED_APPS = [


    'django.contrib.admin',


    'django.contrib.auth',


    'django.contrib.contenttypes',


    'django.contrib.sessions',


    'django.contrib.messages',


    'django.contrib.staticfiles',
    'home',


]



MIDDLEWARE = [


    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware', 

    'django.contrib.sessions.middleware.SessionMiddleware',


    'django.middleware.common.CommonMiddleware',


    'django.middleware.csrf.CsrfViewMiddleware',


    'django.contrib.auth.middleware.AuthenticationMiddleware',


    'django.contrib.messages.middleware.MessageMiddleware',


    'django.middleware.clickjacking.XFrameOptionsMiddleware',


]



ROOT_URLCONF = 'selfWebsite.urls'



TEMPLATES = [


    {


        'BACKEND': 'django.template.backends.django.DjangoTemplates',


        'DIRS': [os.path.join(BASE_DIR,'home/templates')],


        'APP_DIRS': True,


        'OPTIONS': {


            'context_processors': [


                'django.template.context_processors.debug',


                'django.template.context_processors.request',


                'django.contrib.auth.context_processors.auth',


                'django.contrib.messages.context_processors.messages',


            ],


        },


    },


]



WSGI_APPLICATION = 'selfWebsite.wsgi.application'




# Database


# https://docs.djangoproject.com/en/3.2/ref/settings/#databases



DATABASES = {


    'default': {


        'ENGINE': 'django.db.backends.sqlite3',


        'NAME': BASE_DIR / 'db.sqlite3',


    }


}

# db_from_env = dj_database_url.config(conn_max_age=500)
# DATABASES['default'].update(db_from_env)



# Password validation


# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [


    {


        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',


    },


    {


        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',


    },


    {


        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',


    },


    {


        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',


    },


]
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
"""

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 3600
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
"""



# Internationalization


# https://docs.djangoproject.com/en/3.2/topics/i18n/



LANGUAGE_CODE = 'en-us'



TIME_ZONE = 'UTC'



USE_I18N = True



USE_L10N = True



USE_TZ = True




# Static files (CSS, JavaScript, Images)


# https://docs.djangoproject.com/en/3.2/howto/static-files/



STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'



jls_extract_var = BASE_DIR / 'static'
STATICFILES_DIRS = [
    jls_extract_var,
]

# Simplified static file serving.
# https://warehouse.python.org/project/whitenoise/
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key fieldu type


# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST = os.environ['SIB_SMTP_SERVER']
EMAIL_PORT = os.environ['SIB_SMTP_PORT']
EMAIL_HOST_USER = os.environ['SIB_LOGIN']
EMAIL_HOST_PASSWORD = os.environ['SIB_PASS']

