# Generated by Django 3.2 on 2021-12-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_otherthing'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherthing',
            name='Heading',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherthing',
            name='Title',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
