# Generated by Django 3.2 on 2021-12-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211208_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='otherthing',
            name='File',
            field=models.FileField(upload_to='files/'),
        ),
    ]
