# Generated by Django 3.2 on 2021-12-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherthing',
            name='any_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='otherthing',
            name='any_other_html',
            field=models.TextField(blank='True', default='none'),
        ),
        migrations.AlterField(
            model_name='otherthing',
            name='Heading',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
