# Generated by Django 3.2 on 2021-12-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211208_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherthing',
            name='File',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
