# Generated by Django 3.2 on 2021-12-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_otherthing_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherthing',
            name='Heading',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='otherthing',
            name='Title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
